### PR TITLE
Implement shop owner

### PR DESCRIPTION
**Pull request by saenyakorn**
PUT `/api/v1/shops/:shopId/owners`

```
{
  'owner_emails': ['example1@gmail.com', 'example2@gmail.com']
}
```

Also, I want someone to test this endpoint.

## TODO

I didn't check that the current user is the owner of this shop

### CODE REVIEW

**Comment by natTP** [comment]
At first nothing worked because 
- bug in `toShopOwners` (appending to an already allocated array, so the data turns out wrong)
- `ShopOwner` struct didn't have a primary key definition

## CreateShop works now after the fixes.

## GetAllShops and GetShops have the same error

Error message from `lib/repository/shop.go` line 20, 29 (GORM.Preload)

```
can't get shops: ShopOwner: unsupported relations for schema Shop
```

## EditShopOwners still has an error

Error message from `lib/repository/shop.go` line 60 (GORM.Delete)

```
can't edit shop owners: failed to delete shop owner: ERROR: invalid input syntax for type integer: "" (SQLSTATE 22P02)
```

because the list returned form `toShopOwners` is like this (there's no shopId and shop info)

```
[
  {
    "shop_id": "",
    "shop": { "id": 0, "name": "", "omise_recipient_id": null, "owners": null },
    "user_id": "11111111-1111-1111-1111-111111111111",
    "user": {
      "id": "11111111-1111-1111-1111-111111111111",
      "role": "USER",
      "email": "user@example.com",
      "google_id": "user_google_id",
      "omise_customer_id": null,
      "default_payment_method_id": null
    }
  },
  {
    "shop_id": "",
    "shop": { "id": 0, "name": "", "omise_recipient_id": null, "owners": null },
    "user_id": "b3f4bc1e-613a-4d66-8d12-1fc87346e080",
    "user": {
      "id": "b3f4bc1e-613a-4d66-8d12-1fc87346e080",
      "role": "USER",
      "email": "joppy.pgh@gmail.com",
      "google_id": "xxx",
      "omise_customer_id": null,
      "default_payment_method_id": null
    }
  }
]
```

## The rest work as expected.

**Comment by saenyakorn** [comment]
`EditShopOwner` and `DeleteShop` have bugs. Also, `GetAllShops` has the wrong association field. Fixed

**Comment by saenyakorn** [comment]
`toShopOwners` didn't preload `Shop` which means Gorm will replace the value with `zero-value`. In this case, 0 for `shopId` and `0`, `null`, `""` for `shop`

**Comment by natTP** [comment]
`EditShopOwners` behavior right now (not sure if intended)

case1
- suppose the shop has 2 owners, say "user@example.com" and "admin@example.com"
- we want to edit to only 1 owner, send request with "user@example.com"
- the result is still  "user@example.com" and "admin@example.com"

case2
- suppose the shop has 2 owners, say "user@example.com" and "admin@example.com"
- we want to edit to 1 owner not in these two, send request with "newuser@example.com"
- the result is 3 owners "user@example.com", "admin@example.com", and  "newuser@example.com"

The rest are ok

**Comment by saenyakorn** [comment]
Fixed

**Comment by saenyakorn** [comment]
I forgot that we can remove all owners in a single command.

**Review by natTP — APPROVED** [review]
LGTM

**Comment by bombnp** [comment]
asked by @saenyakorn to press merge

**Pull request merged**
